imports:
    - { resource: tables.yml }

services:
    phpbb.googleanalytics.listener:
        class: phpbb\googleanalytics\event\listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbb.googleanalytics.admin.controller:
        class: phpbb\googleanalytics\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - @phpbb.googleanalytics.operator
            - %core.root_path%
            - %core.php_ext%

    phpbb.googleanalytics.controller:
        class: phpbb\googleanalytics\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @phpbb.googleanalytics.operator
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    phpbb.googleanalytics.table_lock:
        class: phpbb\lock\db
        arguments:
            - googleanalytics.table_lock.googleanalytics_table
            - @config
            - @dbal.conn

